allowBuilds:
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - ws@8.20.1
  - '@sveltejs/kit@2.61.1'
  - cookie@0.7.0

overrides:
  chokidar: '>=5'
  cookie@<0.7.0: ^0.7.0
  semver: '>=7'
  ws@>=8.0.0 <8.20.1: ^8.20.1

trustPolicy: no-downgrade
