name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          check-latest: true
          package-manager-cache: false

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - uses: oven-sh/setup-bun@v2

      - name: lint
        run: bun run --bun lint

      - name: build
        run: bun run --bun build
